ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [
      com.adrianobispo.HttpKt.configureHttp
      com.adrianobispo.SerializationKt.configureSerialization
      com.adrianobispo.SecurityKt.configureSecurity
      com.adrianobispo.PostgresKt.configurePostgres
      com.adrianobispo.ExposedKt.configureExposed
      com.adrianobispo.KoinKt.configureKoin
      com.adrianobispo.StatusPagesKt.configureStatusPages
      com.adrianobispo.RoutingKt.configureRouting
    ]
  }
}